site_name: Julie Boyer's Personal Site
site_description: Knowledge acquisition personal's notes
repo_url: https://github.com/boyerjulie/boyerjulie.github.io/
docs_dir: docs
site_dir: public
edit_uri: edit/main/docs
copyright: Copyright &copy; 2025 Julie Boyer

theme: 
  name: material
  logo: images/logo.drawio.png
  favicon: images/logo-blue.drawio.png
  palette:
    scheme: default
    # primary: blue
  language: en
  features:
      - content.code.annotate
      - content.code.annotations
      - content.code.copy
      - content.tooltips
      - content.tabs.link
      - search.highlight
      - search.suggest
      - navigation.instant
      - navigation.instant.progress
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.tracking
      - navigation.sections
      - navigation.expand
      - navigation.footer
      - navigation.tabs.sticky
      - navigation.top
extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/boyerjulie'
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/julie-boyer-657a8b294/'
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - mkdocstrings
  #- mermaid2
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - tables
  - md_in_html
  - pymdownx.smartsymbols
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: 
    - About: index.md
    - Skills: skills.md
    - Projects: projects/index.md
    - Resume: resume.md